### ISSUE TITLE
Beginners ask for help

### ISSUE THREAD

**Issue by singdoo** [tobymao/saq#103]
Hello, great gods, my previous script used asyncio.Queue and list to achieve asynchronous tasks, accidentally brushed to the saq,web function attracted me, to be able to check the progress of the task in real time, which is good. 
But I do not know how to change my script to use saq to achieve, I am not bug, and I do not know who to communicate, I take the liberty of sending it to issues inside is OK?

**Comment by tobymao** [comment]
you can join my slack channel and ask questions tobikodata.com/slack
