### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by lunden23** [tobymao/saq#117]
Hi, the methods

loop.add_signal_handler()
loop.remove_signal_handler()

are not supported on Windows per the asyncio documentation (see here: https://docs.python.org/3/library/asyncio-platforms.html#asyncio-windows-subprocess). For Celery it is possible to circumvent this by installing the gevent package and setting the "--pool=gevent" argument for the worker process.

I was wondering if it is possible to implement a similar argument for the SAQ settings or if that is out of scope? Thanks.

**Comment by tobymao** [comment]
windows was already supported 

    SIGNALS = [signal.SIGINT, signal.SIGTERM] if os.name != "nt" else [signal.SIGTERM]

did something here change?

**Comment by tobymao** [comment]
closing this as out of scope for now
