### ISSUE TITLE
404 not found (task in web view)

### ISSUE THREAD

**Issue by radurevutchi** [tobymao/saq#125]
Getting `404 not found` when clicking on one of my tasks in the web UI. Can't find any documentation on this. My setup follows the tutorial code exactly. I'm hosting in my own web service (aka not pass in the `--web` flag).

`# Mount background SAQ scheduler
app.mount("/scheduler", saq_web("/scheduler", queues=[saq_queue]))`

<img width="1436" alt="Screenshot 2024-06-10 at 02 10 04" src="https://github.com/tobymao/saq/assets/25625538/737a68e7-9976-4f91-9d4f-f663673c25c5">
<img width="1436" alt="Screenshot 2024-06-10 at 02 10 59" src="https://github.com/tobymao/saq/assets/25625538/cfb9acc9-f676-46b2-905c-864cb70e74d2">

**Comment by tobymao** [comment]
can you provide a minimal script for reproduction?

**Comment by radurevutchi** [comment]
`main.py`
```
from fastapi import FastAPI
from saq.web.starlette import saq_web
from app.saq.saq import queue as saq_queue


app = FastAPI()

# Mount background SAQ scheduler
app.mount("/scheduler", saq_web("/scheduler", queues=[saq_queue]))
```

`saq.py`
```
from saq import CronJob, Queue
from saq.types import Context
from app.core.settings import Settings

def update_products_daily(ctx: Context):
    print("Updated")

cron_jobs = [
    CronJob(update_products_daily, cron="* * * * *"),  # Every minute
]
queue = Queue.from_url(Settings.REDIS_URL)
settings = {"queue": queue, "functions": [], "concurrency": 10, "cron_jobs": cron_jobs}
```

**Comment by radurevutchi** [comment]
<img width="1440" alt="Screenshot 2024-06-10 at 17 59 48" src="https://github.com/tobymao/saq/assets/25625538/a5e628eb-079b-4141-9a84-b430ec939aa9">
