### ISSUE TITLE
Version mismatch in documentation

### ISSUE THREAD

**Issue by Seemone** [tobymao/saq#136]
Documentation version mentions 0.12.3 as latest, but SAQ has 0.13.3

**Comment by tobymao** [comment]
i'm not sure how to fix this

**Comment by tobymao** [comment]
@grigi could you help me figure out and fix this? i don't know how docs are deployed or why they aren't updating.

**Comment by grigi** [comment]
I did manually click the build docs option, but I see a lot of features have been added (like using Postgres as a queue).
I'll see if I have time to update some of the docs, but the PG feature changes a lot of assumptions made before.

**Comment by tobymao** [comment]
@grigi i changed the master branch to main, and i think i broke the read the docs, can you take a look?sorry about that

**Comment by tobymao** [comment]
@grigi ok i think readthedocs finally updated their ui

**Comment by grigi** [comment]
Hi @tobymao seems that their UI took a while to realise a new branch exists.

You still need to setup the Github integration. Either go to https://readthedocs.org/accounts/3rdparty/ and setup github integration directly.

or

Go to https://github.com/tobymao/saq/settings/hooks/new and enter the url and secret from https://readthedocs.org/dashboard/saq-py/integrations/278319/
And instruct GitHub to use that webhook when an update to main happens.


This should setup readthedocs to automatically have up-to-date docs.

If you need to you're welcome to delete the webhook I setup.

**Comment by tobymao** [comment]
ok, i set up the web hook

**Comment by grigi** [comment]
Sweet! Hopefully documentation is now automated for the future :+1:
