### ISSUE TITLE
0.14 is broken

### ISSUE THREAD

**Issue by conanjen** [tobymao/saq#137]
with the refactor there no longer exists an `saq.queue` module, as seen here: https://github.com/tobymao/saq/blob/1aefd71e53e7e20b952a671cdd089bd9ea5c6895/saq/__init__.py#L6

**Comment by acreux** [comment]
The `tar.gz` downloaded from from https://pypi.org/project/saq/#fileshas no `queue` folder, thus failing the basic from `saq.queue import Queue`
<img width="274" alt="image" src="https://github.com/user-attachments/assets/e15f013d-33bc-4920-8b14-18eb7dbd0fd6">


However, the `tar.gz` downloaded from https://github.com/tobymao/saq/releases/tag/v0.14.0 has the `queue` folder
<img width="244" alt="image" src="https://github.com/user-attachments/assets/7314204b-c138-41b1-9c86-623aeb7e0c57">

**Comment by xiaoyu-meng-mxy** [comment]
Can we do a release?
