### ISSUE TITLE
Static not found when bound /monitor to app

### ISSUE THREAD

**Issue by N1LEX** [tobymao/saq#164]
The web ui is blank

app.mount("/monitor", saq_web("/monitor", queues=[queue]))

/monitor/
/monitor/static/pico.min.css 404 Not Found
/monitor/static/snabbdom.js 404 Not Found

Please, help

**Comment by tobymao** [comment]
are you on the latest version of saq? need more information to help you out. closing for now.

**Comment by N1LEX** [comment]
> are you on the latest version of saq? need more information to help you out. closing for now.

I'm on the latest version (0.16.4)

web container command: 
`uvicorn app.main:app --host  0.0.0.0 --port 8000 --reload

`
Whetheless, it works on saq container:
`saq rassrochki_api.background_tasks.settings.background_task_settings --web
`

**Comment by N1LEX** [comment]
@tobymao any ideas?

**Comment by N1LEX** [comment]
Sorry, everything is ok
