### ISSUE TITLE
Starlette web not working

### ISSUE THREAD

**Issue by aleixrodriala** [tobymao/saq#168]
Because of: https://github.com/tobymao/saq/commit/8f4aa33c16acea98fa1641da7e914bd224eb94c1, now the starlette website is not loading because can't find pico.min.css or snabbdom.js

![image](https://github.com/user-attachments/assets/8815875f-b337-4ccb-b9dc-41386852f3b9)

I'm creating a fix, should we just hardcode that if it's any of the files it gets the .gz path or what approach do you want to take?

Thanks for your work, it's an amazing library :)

**Comment by tobymao** [comment]
i don’t have a preference, but feel free to make a pr and we can iterate
