### ISSUE TITLE
Conflict with Debuggers

### ISSUE THREAD

**Issue by aleixrodriala** [tobymao/saq#174]
When trying to run ipdb; ipdb.set_trace() in a task I get the following:

```  python
File "/mnt/c/Users/aleix/Documents/GitHub/domain-watcher/app/watcher/fuzzer/url_fuzzer.py", line 134, in check_response_active
    response = Response(response)
  File "/usr/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit 
```

**Context:**

- Running command: 

``` saq app.tasks.settings --workers 8 ```

- Code: 

``` python
  def check_response_active(self, response, signature):
        if not response:
            return False
        
        import ipdb; ipdb.set_trace()
```

Is there any way to debug tasks while running the saq queue? 

Thanks

**Comment by tobymao** [comment]
maybe not with the workers settings, but you could use print statements

**Comment by barakalon** [comment]
For debugging, I wouldn't use the workers setting

**Comment by aleixrodriala** [comment]
> For debugging, I wouldn't use the workers setting

In my case I have a task that goes through multiple stages and from one queue to another, how would you debug this then for example?

Thanks

**Comment by barakalon** [comment]
saq uses asyncio and one worker should support multiple concurrent tasks. So simply removing that setting should work, unless you’ve got some more complex setup I’m not aware of?
