### ISSUE TITLE
Requeuing unique tasks with different parameters

### ISSUE THREAD

**Issue by aleixrodriala** [tobymao/saq#181]
Good night,

I am designing a system where I need tasks to be unique on each queue, and I have multiple queues that each one represent the status of the task it's going on, i'm monitoring network traffic.

The status and queues are the following: dns -> url -> requests. 

I need to do the same task multiple times untill I get certain content or match some filters, for example could do 5 times the dns function, then goes to the url queue etc.

Untill now I was just not having a unique key on each queue and just queuing again with a different uuid, but I would like to have more control about the queue and have a unique key for each domain or url processed.

I have been looking at how the library works internally and tried to finish the task before queuing again: (I know this is not the best way, because probably the library after I finish it, tries to finish it itself, but I didn't find a way to queue the task with different parameters, not retrying)

```python
await ctx['job'].finish(status)
await asyncio.sleep(2)
```
I even tried to add some sleep just to test if that was the issue, but when I finish the task and queue it again with same id the task gets queued, but it's not executed.

I run this after finishing the task
```python
job = await queue_obj.enqueue(*args, **kwargs)
if job:
    print (f'Job {job.id} enqueued successfully')
else:
    raise Exception(f'Failed to enqueue task {function} with args {args} and kwargs {kwargs}')
```

And I don't get any exception, still the task does not run.

Logs:
```
Finishing task saq:job:opendir:https://eurolanderasmus.web-catalog.biz/
Finishing task saq:job:opendir:https://www.eurolanderasmus.web-catalog.biz/
Enqueuing task monitor_open_dir with args ('monitor_open_dir',) and kwargs {'url': 'https://eurolanderasmus.web-catalog.biz/', 'potential': 100, 'last_hash': 'd60ba7b7bfd6a8c7073752fb4f78ffd382ee9972bc46e5f0022b0de6f3b3af58', 'last_files_hash': '6dfb636dd6cb254a07a813d22e0f196bcfa3c4f99795e500a94114448ee54b14', 'scheduled': 1729718512.7558277, 'patience': 0, 'timeout': 600, 'key': 'https://eurolanderasmus.web-catalog.biz/'}
Job saq:job:opendir:https://eurolanderasmus.web-catalog.biz/ enqueued successfully
```

Thanks for your time, and I can maybe work on something myself if you tell me what we can implement to make this a possibility of having unique retries with different parameters.

**Comment by tobymao** [comment]
i'm not exactly sure what you're trying to do. maybe you can provide a fully reproducible minimal script

i think you should be able to re-enqueue a job if it is complete, another possibility is you could use group_key which is postgres only.

**Comment by aleixrodriala** [comment]
No problem, I'm doing a different approach now to enqueue again in the after_process part, so the task is already outside of the queue.

If I get any other issues I'll tell you, Thanks.
