### ISSUE TITLE
Question: What's the best way to limit concurrency per job name

### ISSUE THREAD

**Issue by evgenii-moriakhin** [tobymao/saq#183]
I want to use the saq library and limit the number of concurrent job not globally per worker, but specifically per job name. If I put a semaphore inside the job, the worker would still dequeue jobs before waiting on the semaphore, which doesn't solve my issue with multiple workers - other workers might be idle when they could be working on different jobs. So I'm thinking about running one saq worker per job name. This way, the concurrency option would work as I want it to. My questions are:

What's the overhead of running separate workers for different job names?
Is it a reasonable approach to use saq this way with different queue backends (redis/postgres)?
Is there an easier way to implement per-job-name concurrency?
Looking for advice on the best approach to handle this use case.

**Comment by evgenii-moriakhin** [comment]
I have an idea to check "job concurrency limit" for specific jobs before calling .dequeue() in the worker. This would compare against the current number of running jobs (filtered by name). If the number of running jobs exceeds the limit, we would pass exclude_names=["name1", "name2"] argument to .dequeue().While this seems relatively straightforward to implement with PostgreSQL, I'm concerned there might be issues with Redis implementation.

**Comment by barakalon** [comment]
We likely won't add support for per-job concurrency. I think a queue per job is the way to go. 

> What's the overhead of running separate workers for different job names?
Different _queues_, more precisely. Overhead should be minimal - it mostly costs the extra connections.

> Is it a reasonable approach to use saq this way with different queue backends (redis/postgres)?
I think so, yes

> Is there an easier way to implement per-job-name concurrency?
Not that I can think of, with saq.

**Comment by barakalon** [comment]
Closing as not planned, but feel free to continue the discussion

**Comment by evgenii-moriakhin** [comment]
Let me share my thoughts on this. Postgres has a job priority system implemented. If we start using different queues for each job name, we'll get job concurrency limits but lose priorities. And note that priorities are implemented only for Postgres. Actually, both features are similar in their core functionality (database query for data sorting vs database query for job exclusion by name).

Basically, the job concurrency limit feature would feel natural in Postgres implementation and would have the same right to exist as the priority mechanism.

Since priority functionality already exists, the Postgres queue implementation already "stands out" among queues. And specifically for Postgres, implementing job concurrency limits wouldn't be a problem.

These are just my thoughts, I'm not pushing for this to be done, and I understand that the API would have more changes than with priorities. If saq were Postgres-only, it would be easier to argue for adding this feature.

**Comment by barakalon** [comment]
That’s fair.

I’m mostly familiar with the redis implementation, so maybe I’m old guard now. I’ll yield to @tobymao .

Might help to share more info on the use case, why this is valuable, etc. In general I feel like we should be protective about keeping the simple in “simple async queues”.

**Comment by evgenii-moriakhin** [comment]
My use cases for saq are related to a virtualization platform that needs to run operations on compute nodes, dealing with expensive physical operations (storage systems, disks).
That's why both priorities and concurrency limits for specific heavy jobs are very useful.

Yes, I agree that saq should remain simple and won't cover all possible needs.

I chose saq specifically because it's simple, and if business requires something unusual, I can always modify its implementation without much effort.

Therefore, I also truly believe saq SAQ should strive for simplicity rather than complexity. It's up to you - the library authors - to decide what functionality should be included in this "simplicity".

Simplicity goes great with flexibility (like the recent queues refactoring into an abstract Queue class - which is excellent).

**Comment by tobymao** [comment]
have you checked out the group parameter? that allows for only one job of a group to be dequeued at once

**Comment by evgenii-moriakhin** [comment]
No, I haven't checked it, you're right - I didn't understand its usage at first. Indeed, it works as concurrency_limit=1 for a specific group (which suits my needs). Thank you
