### ISSUE TITLE
--check is really slow

### ISSUE THREAD

**Issue by langchain-infra** [tobymao/saq#186]
Hi,

We really love SAQ and use it for several workloads. Recently were looking into adding healthchecks for saq deployments and running into really long runtimes for the --check functionality. Is this expected? Is there a better approach for adding healthchecks to our deployments?

Example below:

```
/code/smith-backend # time saq app.workers.queues.ingestion_worker.settings --check
real    0m 42.14s
user    0m 28.50s
sys     0m 2.93s
```

**Comment by tobymao** [comment]
it's probably whatever is loading your settings, are you doing a lot of work there?

```
time saq examples.simple.settings --check

real    0m0.225s
user    0m0.198s
sys     0m0.024s
```
