### ISSUE TITLE
Error Future pending attached to different loop

### ISSUE THREAD

**Issue by aleixrodriala** [tobymao/saq#187]
Hello, I'm getting this message randomly in a queue, i'm using multiple workers. 
```python
ERROR:saq:Error processing job None
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/saq/worker.py", line 263, in process
    job = await self.queue.dequeue(self.dequeue_timeout)
  File "/usr/local/lib/python3.9/site-packages/saq/queue/redis.py", line 353, in dequeue
    return await self._get_job_by_id(job_id)
  File "/usr/local/lib/python3.9/site-packages/saq/queue/redis.py", line 313, in _get_job_by_id
    async with self._op_sem:
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
RuntimeError: Task <Task pending name='process' coro=<Worker.process() running at /usr/local/lib/python3.9/site-packages/saq/worker.py:263> cb=[Worker._process()]> got Future <Future pending> attached to a different loop
```

I've checked the implementation, and this issue could be because Queue instances could be shared between processes because of how the Queue instance is created in the settings instead of inside the worker. 

I think a better approach would be to create the new Queue instance when starting the worker, like here by passing only the url and the kind of queue if it's redis postgres, to ensure Queue instances are not shared between processes.

https://github.com/tobymao/saq/blob/f7c5d9d9f4772b9db741a7507a2843e1134dd5a7/saq/worker.py#L387

Just in case I'm missing something out:

My settings file is on \_\_init\_\_.py which might be causing the issue, because instance is created when importing the module. 
And the command to run the workers is:
```
app.tasks.settings_opendir --workers 8
```
Although I have to say that I have been using this setup for a while and the error happens randomly, might be a race condition or something like that.

Tell me if my implementation is not right and I should change something or if you want me to change how the implementation works, we could do some approach to not break backwards compatibility and that the Queue.from_url object just returns something that then is used to create the queue instance inside the worker.

Thanks for this amazing library,
Aleix

```python
#/app/tasks/__init__.py

async def startup_telegram(ctx=None):
    await TelegramClient.init_bot('new')
async def shutdown(ctx):
    await TelegramClient.close_bot()
    
telegram_queue = Queue.from_url(config.REDIS_URL, name=QueueNames.TELEGRAM)

settings_telegram = {
    "queue": telegram_queue,
    "functions": [monitor_telegram],
    "concurrency": 20,
    "startup": startup_telegram,
    "shutdown": shutdown,
    "after_process": after_process
}

**Comment by tobymao** [comment]
can you make a fully reproducible minimal example?

**Comment by aleixrodriala** [comment]
I tried but can't reproduce it, I'm waiting for it to happen again.

Investigating further the code, it should be fine because the settings module is imported after creating the process, so the Queue instance is created after the process has been forked, not sharing memory space, so same Queue instance should never be shared across the workers (processes).

So I can think only of two options could be causing this:
- Python somehow shares this instances in memory between different processes, so this would explain different event loops sharing same semaphore instance
-One process has multiple event loops and a semaphore future gets attached to a different loop.

Maybe you know better what could be happening with the info I gave you

**Comment by tobymao** [comment]
its probably got something to do with how you’re using the library.

**Comment by aleixrodriala** [comment]
I showed you how I'm using it, anything wrong?

**Comment by tobymao** [comment]
there’s probably more to it that you’re not showing that is the cause

**Comment by aleixrodriala** [comment]
It was related to the Docker python-3.9-slim version, the postgre example didn't even start running. Can't investigate further at the moment but setting the image to python-3.10 solved the issue, if it can help anyone
