### ISSUE TITLE
Option to restart worker based on metrics (i.e. memory consumption / tasks processed)

### ISSUE THREAD

**Issue by provinzkraut** [tobymao/saq#190]
It would be very convenient to have the option to restart a worker process once it hits a certain threshold, such as memory consumption or number of tasks processed. In long-running deployments, this can help with things such as memory leaks that are out of control of the application.

<hr>

Celery allows this with their [`worker_max_tasks_per_child`](https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-max-tasks-per-child) and [`worker_max_memory_per_child`](https://docs.celeryq.dev/en/stable/userguide/configuration.html#worker-max-memory-per-child), which I default all my celery deployments to. Migrating to saq, this has been a bit of a holdup.

If this is something you'd consider adding, I'd be happy to contribute a PR :)

**Comment by tobymao** [comment]
sure, i'm open to it, feel free to make a PR. thank you.

closing as not planned since core team won't work on it. but will work with you to get it in.
