### ISSUE TITLE
Passing dynamic settings

### ISSUE THREAD

**Issue by maxyme-perceiv** [tobymao/saq#192]
Hi, would it be possible to pass settings dynamically when starting the worker? For example:

```
def start(
    settings_obj: dict = None, 
    settings: Path = None,
    web: bool = False,
    extra_web_settings: list[str] | None = None,
    port: int = 8080,
) -> None:
    if settings_obj is None:
        settings_obj = import_settings(settings)
```
This would allow starting the worker from another process with dynamic settings, instead of writing them to a file and then passing the path. 

Also, as an aside, I think we could pass the settings as a Path object rather than a string.

thanks!

**Comment by tobymao** [comment]
possibly? feel free to make a non-breaking PR that demonstrates this
