### ISSUE TITLE
Slow operation for retry when queued list is large, using LREM

### ISSUE THREAD

**Issue by akira** [tobymao/saq#195]
Seeing an issue with a slow operation in the retry path.  I see that the code is using [LREM](https://redis.io/docs/latest/commands/lrem/) for removing an item from the queued list when retrying. 
https://github.com/tobymao/saq/blob/main/saq/queue/redis.py#L416
This command is marked as `slow` in Redis as it's O(N+M) to the size of the queue.   

This can be particularly an issue when the queued list is large and there's a 
a lot of tasks retrying / failing (which could happen during a degraded system state especially). 
For example, trying this locally, if the queue size is 500k, it would slow down to a few hundred total operations per second.
The other issue is that it could also lock up other operations on the Redis server (for example other queues, caching, etc).  
This is especially worse if the item is not in the list - which seems the expected case? Not sure on when it's expected
that the job being processed would also be in the queued list.   

Fan of Saq so far, wanted to see if any there could be any potential improvements to the performance of this code path. Thanks!

**Comment by tobymao** [comment]
i'm not sure if this is possible because the core data structure is to use lists for the main queue using blmove to _queued and _active

primary development on saq has moved to postgres because it's much easier to build a robust queue on there. so i'm going to mark this as not planned, but happy to discuss or open to contribution if you want to fix this.

but i'm not planning to put much effort into redis as postgres provides much more capabalities.

**Comment by akira** [comment]
Question on this - for the retry use case, the item would already be move from queued to active using blmove, what's the 
case for scanning the `self._queued` in addition to removing from active?
```
async def _retry(self, job: Job, error: str | None) -> None:
        job_id = job.id
        next_retry_delay = job.next_retry_delay()

        async with self.redis.pipeline(transaction=True) as pipe:
            pipe = pipe.lrem(self._active, 1, job_id)
            pipe = pipe.lrem(self._queued, 1, job_id)
```

**Comment by tobymao** [comment]
my guess is that this was added to ensure that everything is wiped clean. even if it’s not in the active list. so retrying something that’s still queued. if you can prove that is unnecessary, we can remove it
