### ISSUE TITLE
Best way to globally override Job defaults ?

### ISSUE THREAD

**Issue by paul-finary** [tobymao/saq#30]
Hi,

I'd like to change the default parameters for all my Jobs (e.g. generate a key via the job name and its arguments, setting the ttl to -1, increasing the timeout, etc.), but I have a bunch of jobs (10+).

I thought about defining sort of a `default_job_kwargs` and passing it to `enqueue()`, but it looks easy to forget and thus error-prone. Or I also thought about defining my jobs as instances of Job instead of functions, and using this `default_job_kwargs` here instead of when enqueueing them, but then again, easy to forget when defining a new job.

Is there a preferred way to globally override the defaults instead of passing those arguments every time I enqueue/implement a job ?

If that's a feature you think would be good to have, do you have an opinion/idea about how it should be implemented ?

Thanks for the help!

**Comment by tobymao** [comment]
The way I do this is as you described, I have a default job kwargs that I override when enqueueing jobs. Another way you can do it is to make a subclass of job with the defaults you want. i don't think it's necessary for another global way to do this. But happy to chat more.

**Comment by barakalon** [comment]
Having SAQ configuration for certain defaults might make sense to me (e.g. `default_ttl` or `default_timeout`). Maybe as attributes on the Queue.

Others might be messier (e.g. "generate a key via the job name and its arguments"). That sounds like it depends on some application specific logic. There _is_ currently a "before_enqueue" hook for Queues where you could inject such logic... but that feels like overkill.

What about regular ol' composition?:

```python
class MyQueue:
    def __init__(self, saq_queue):
        self.saq_queue

    async def enqueue(self, job_or_func, **kwargs):
        default_kwargs = {
            "ttl": -1,
            "timeout": ...,
            "key": get_job_key(job_or_func, **kwargs)
        }
        default_kwargs.update(kwargs)
        return await self.saq_queue(job_or_func, **default_kwargs)
```

Or regular ol' inheritance?:

```python
class MyQueue(Queue):
    async def enqueue(self, job_or_func, **kwargs):
        default_kwargs = {
            "ttl": -1,
            "timeout": ...,
            "key": get_job_key(job_or_func, **kwargs)
        }
        default_kwargs.update(kwargs)
        return await super().enqueue(job_or_func, **default_kwargs)
```

In my experience, complex layers of global configuration is more "error prone" than just setting the config explicitly in code. I also think it's often a good practice to wrap broad third party interfaces with narrow application-specific interfaces.

**Comment by paul-finary** [comment]
Thanks for the quick answers, I ended up going the inheritance way: with this approach there's only one place to define those default kwargs in my app.
