### ISSUE TITLE
Queue timeout

### ISSUE THREAD

**Issue by sondrelg** [tobymao/saq#35]
Hi!

I've just sat down to take a stab at rewriting one of our services from arq to saq, and it's been going well! Thanks for creating this :clap: Was also happy to see that it's compatible with the new redis v4.2+ stuff!

I just have one question I wasn't easily able to answer: is there a way to set a queue-specific timeout? I have two queues, where one is reserved for long running jobs. I'd rather not pass timeout to every `enqueue` call if possible :slightly_smiling_face: Can I specify a timeout either in the settings, or on the queue-instance?

**Comment by tobymao** [comment]
check out the discussion here

https://github.com/tobymao/saq/issues/30

i don't have a queue level setting to keep things simple, but it's easy enough to build your own abstraction. happy to chat more!

**Comment by sondrelg** [comment]
Thanks, this looks good!
