### ISSUE TITLE
Add authentication to web dashboard

### ISSUE THREAD

**Issue by MrAwesomeRocks** [tobymao/saq#38]
It would be nice to have some authentication for the web dashboard, like flower, so not everyone can start/stop/retry tasks.

It doesn't have to be anything fancy, [HTTP Basic Auth](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic_authentication_scheme) with only one user should be enough.

Alternatively, each request could require a `?token=XXX` query parameter, where the token is passed in through an environment variable.

**Comment by tobymao** [comment]
you can now do basic auth

```
AUTH_USER=toby AUTH_PASSWORD=password python -m saq examples.simple.settings --web
```

**Comment by MrAwesomeRocks** [comment]
Wow that was fast. Thank you very much!

I'm really loving the library by the way. It just works. Very little setup, and everything works great.

**Comment by tobymao** [comment]
glad to hear it
