### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by MrAwesomeRocks** [tobymao/saq#39]
It would be really great if this project had PEP 484 type hints, for better editor support and integration with Mypy.

I'd be willing to help with this.

**Comment by tobymao** [comment]
i’m against types annotations

**Comment by MrAwesomeRocks** [comment]
How come?

**Comment by tobymao** [comment]
python is not a typed language and the types don’t do anything, their fancy comments. i find them more of a hindrance than helpful. 

most type errors are due to having None. but  python doesn’t have a true option type with operators like map such as those found in scala.

**Comment by peterschutt** [comment]
@tobymao I respect your position here, but would you mind if I created `saq-stubs` and publish to pypi so users can opt into using the stubs if they choose?

**Comment by tobymao** [comment]
@peterschutt i've decided i cannot win this battle, i will accept a PR to saq directly if you add types and mypy to the whole repo.

**Comment by peterschutt** [comment]
I'm sorry to be straw that broke the camel's back :laughing: - there really is no escaping it.

FWIW, I've been very comfortable using the library without annotations - the code is clean, concise and easy to follow. I just experience issue when trying to use a consistent set of tooling across apps.

I'll start with a stubs package, and once I have enough detail in the stubs to be useful, then we can see what it looks like in-line.

**Comment by tobymao** [comment]
i'd much prefer just doing it in saq as opposed to doing stubs, let me know what i can do to help you make that happen

**Comment by peterschutt** [comment]
OK great, thanks.

I'll probably end up trying a tool like [MonkeyType](https://github.com/instagram/MonkeyType) just to see if that can get us past the low-hanging fruit. I'll make a draft PR and we can go from there.
