### ISSUE TITLE
Readiness and liveness probes

### ISSUE THREAD

**Issue by sondrelg** [tobymao/saq#44]
Hi :wave: 

I just wanted to ask a quick question: have you spent any time considering what effective liveness/readiness probes might look like for saq @tobymao? 

For a web server I think convention is to ping a healthcheck endpoint, or something equivalent. I'm not aware of an obvious equivalent for a task runner.

I'm sure this has been answered for other task runners, and I'm planning to do a little research now. Just asking in case you've either got an answer ready, or if there's an implementation detail unique to saq that would make sense to use for this :+1: 

(I'm not running the aiohttp part of saq, so I don't want to rely on that :slightly_smiling_face: )

**Comment by tobymao** [comment]
you can either use the web sever or the api call here

https://github.com/tobymao/saq/blob/877c5dd5a72be4b4c41d9244a6bcd795982e7650/saq/worker.py#L340

**Comment by sondrelg** [comment]
I see now there's a `--check` option as well :+1: I'll use that :slightly_smiling_face: Thanks!

**Comment by tobymao** [comment]
keep in mind the downside of using a cli is it has to load your app. so if that takes time to load, like 3+ seconds, it could cause problems. my team ran into that which is why i built the web health check.
