### ISSUE TITLE
Mechanism for transferring state from enqueing process to worker

### ISSUE THREAD

**Issue by sondrelg** [tobymao/saq#5]
Hi @tobymao,

The `before_process` and `after_process` hooks are great. Do you think it would also be possible to add an event hook for `on_enqueue`. 

Celery has the `before_task_publish` event - this is really what I'd like to mirror.

```python
# celery example

@before_task_publish.connect
def transfer_correlation_id(headers: Dict[str, str], **kwargs: Any) -> None:
    """
    Attach request ID to the task headers.
    """
    cid = correlation_id.get() 
    if cid:
        headers[header_key] = cid
```

I need to be able to pass state from this event handler, to the worker, so there needs to be some data structure involved that is passed to the worker. Celery uses a plain `dict` I believe.

If you think this is a good idea, I'd also be happy to open a PR for this myself 👍

**Comment by tobymao** [comment]
i'm not sure I understand the use case.

when you do await queue.enqueue(...) you already have the job and so you have access to the job etc.

can you go into a bit more detail about what you need to do?

you could do

await Job(correlation_id=corellation_id.get()).enqueue()

**Comment by sondrelg** [comment]
Yes I understand the confusion. 

You are right, I *could* pass the `correlation_id` to a job directly when queueing a job, but that's not what I want to do; I want to set up automated state transfer in *all* queued jobs 🎉

The correlation ID in this example is a UUID generated in a middleware, for an incoming request. I have a log filter that logs the unique ID in all logs output in the thread for the single request. 

When I queue a job, I want to automatically transfer that ID from the web-server to the worker, before:

- using the `before_process` event handler to set the unique ID to be logged for all logs output by the worker
- using the `after_process` event handler to clean up

More than that, I would really like to build this into [this package](https://github.com/snok/asgi-correlation-id) so that this whole thing just works out of the box 🙂

**Comment by tobymao** [comment]
ok sounds good, perhaps you can just add a context variable to job and then do the before enqueue hook, happy to review your PR for this

**Comment by tobymao** [comment]
closing this issue for now, again, happy to review a PR when it's up
