### ISSUE TITLE
Question: How to run Web monitoring component as a separate process (without workers)

### ISSUE THREAD

**Issue by pavdwest** [tobymao/saq#53]
I'd like to be able to run the Web queue monitor as a separate process to multiple worker processes. I've tried using `--workers 0` but it doesn't seem to respect the value of 0 and still picks up tasks from the queue.

This would be useful in docker setups where you'd have a service that serves up only the Web monitoring (without any workers) and then multiple instances of a Worker service. The issue here is that the worker instances conflict with the port they're exposing.

**Comment by tobymao** [comment]
the intent was to have one of the workers serve web while processing and the others don’t serve web.

feel free to submit a pr to have workers 0 be respected
