### ISSUE TITLE
website documentation for saq 

### ISSUE THREAD

**Issue by Kokoserver** [tobymao/saq#59]
i'm very happy to see this project. but it will be nice to have a website the documentation

**Comment by tobymao** [comment]
not planned. may eventually do a pdoc website with github hosting

**Comment by Kokoserver** [comment]
alight well done

**Comment by Mattwmaster58** [comment]
It would be nice to see documentation, doesn't matter to me where it's hosted. I think it would people (myself included) more confidence in picking this over RQ
