### ISSUE TITLE
Novice question

### ISSUE THREAD

**Issue by Kokoserver** [tobymao/saq#60]
I'm new to microservice word, but is required of me from my work, we have an ecommerce that we want to migrate to microservice architecture. so the question is if i have one microservice in another machine and another in other machine. so if am using saq which i should say than you because it has everything i love have tried it and is very straight forward, how do i make another machine know there is a job you need to work on. thanks

**Comment by tobymao** [comment]
if you point saq to the same redis instance, it can process jobs. have each microservice share the same saq processing code
