### ISSUE TITLE
Relax redis dependency

### ISSUE THREAD

**Issue by gazorby** [tobymao/saq#61]
Hi @tobymao, great project!

redis dependency is specified as `>4.2,<4.4`. Any reason why we need `<4.4`? Not a big deal but the readme only mention `>4.2`

**Comment by pahrohfit** [comment]
It was failing in a few areas, as well as tossing up lots of uncaught exceptions. I just submitted a PR(#62) a few minutes ago which includes fixes and relaxed dependency (<5.0).

**Comment by tobymao** [comment]
thanks yea, redis 4.4 broke a lot of projects with their changes to errors / cancellations.

**Comment by tobymao** [comment]
https://github.com/redis/redis-py/pull/2104
