### ISSUE TITLE
Support redis 4.5.x?

### ISSUE THREAD

**Issue by lqmanh** [tobymao/saq#63]
1. There's a race condition bug with redis <=4.4.3 and <=4.5.3, which was addressed in the next bugfix versions.
2. I'm trying to install litestar 2.0.0alpha3, which depends on redis >=4.4.4 and >=4.5.4 (yeah they explicitly require so to avoid that race condition bug).

**Comment by tobymao** [comment]
redis is broke stuff in 4.4

is it fixed?

https://github.com/redis/redis-py/pull/2104
