### ISSUE TITLE
Redis requirement ranges

### ISSUE THREAD

**Issue by sondrelg** [tobymao/saq#67]
Hi @tobymao, sorry for the issue spam.

Would you mind unpinning the redis requirement upper-bound? I see the [original issue](https://github.com/redis/redis-py/pull/2104) is resolved, and I need to be able to run 4.4+ to fix another ][issue](https://github.com/redis/redis-py/issues/2449) I'm having, migrating from a standalone to cluster redis setup :bow: 

Specifically this line: https://github.com/tobymao/saq/blob/master/setup.py#L32

**Comment by tobymao** [comment]
do you know how to do version bounds?
