### ISSUE TITLE
Can I use a custom serializer?

### ISSUE THREAD

**Issue by kindaway** [tobymao/saq#74]
I want to enqueue a job which will have a class from a 3rd party lib. It is not json serializable, but I can serialize it with pickle.dumps and loads without problems. How can I use pickle instead? 

Thanks in advance, kindaway.

**Comment by tobymao** [comment]
set the dump and load lambdas 

https://github.com/tobymao/saq/blob/dcdadbbb8cbde47351cb360053418a1aafe92913/saq/queue.py#L76
