### ISSUE TITLE
Stopping Worker Cancels Running Tasks

### ISSUE THREAD

**Issue by jamesoguyer** [tobymao/saq#75]
Can stopping the worker get an option wait for all tasks to complete rather than cancel them? Would be useful to have a way to block new jobs from being processed and wait for the existing jobs to finish.

    async def stop(self) -> None:
        """Stop the worker and cleanup."""
        self.event.set()
        all_tasks = list(self.tasks)
        self.tasks.clear()
        for task in all_tasks:
            task.cancel()
        await asyncio.gather(*all_tasks, return_exceptions=True)

**Comment by tobymao** [comment]
I have no plans to implement this but happy to accept a well written + tested PR. Happy to help you through it, let me know if you're interested.

**Comment by jamesoguyer** [comment]
Would like to create a PR to help support this. Ran into an issue where updates to machines would take down the workers and cause tasks to be aborted while in progress.

**Comment by tobymao** [comment]
Yea, it's designed to recover, so a shut down worker will cancel jobs immediately, and they'll picked up by other workers. This was the pattern we used.

hit me up on tobikodata.com/slack

**Comment by jamesoguyer** [comment]
No change needed, will design all tasks that use the worker library to be atomic so they can re-run safely if they are aborted halfway through.
