### ISSUE TITLE
Make repository and project itself more friendly for future contributions

### ISSUE THREAD

**Issue by fadedDexofan** [tobymao/saq#94]
I want to try to implement the plan indicated in the title and prepare the repository for future contributions and possible participation in Hacktoberfest 2023.

And so here is the plan in my vision point by point:
1. Move all package and build managing to [PDM](https://github.com/pdm-project/pdm). Something like done recently in [Pydantic](https://github.com/pydantic/pydantic/blob/main/pyproject.toml)
2. Use [Ruff](https://github.com/astral-sh/ruff) and Black (already used) to all code-style checking, linting and formatting.
3. Add pre-commit hooks
4. Revisit type annotations with stricter and more precise mypy configuration
5. Migrate old test suites based on unittest to pytest
6. Write `CONTRIBUTING.md` guide to cover all these steps
7. Add `hacktoberfest` topic to repo 😄

**Comment by fadedDexofan** [comment]
@tobymao need your approvement

**Comment by tobymao** [comment]
> I want to try to implement the plan indicated in the title and prepare the repository for future contributions and possible participation in Hacktoberfest 2023.
>  
> And so here is the plan in my vision point by point:
> 
>     1. Move all package and build managing to [PDM](https://github.com/pdm-project/pdm). Something like done recently in [Pydantic](https://github.com/pydantic/pydantic/blob/main/pyproject.toml)
>   NO
>     2. Use [Ruff](https://github.com/astral-sh/ruff) and Black (already used) to all code-style checking, linting and formatting.
>    YES ( remove everything else except ruff and black )
>     3. Add pre-commit hooks
>     NO
>     4. Revisit type annotations with stricter and more precise mypy configuration
>     YES
>     5. Migrate old test suites based on unittest to pytest
>     NO
>     6. Write `CONTRIBUTING.md` guide to cover all these steps
>     YES
>     7. Add `hacktoberfest` topic to repo 😄
        NO

Happy to discuss, look forward to your PRs.
