### ISSUE TITLE
not working in windows due to asyncio has no add_signal_handler

### ISSUE THREAD

**Issue by sahitono** [tobymao/saq#98]
windows doesn't have signal sigterm like in linux. which caused `NotImplementedError` thrown on running saq 
best solution that i have right now is to skip `add_signal_handler` if os is windows

```python
if os.name != "nt":
    for signum in self.SIGNALS:
        loop.add_signal_handler(signum, self.event.set)
```

**Comment by tobymao** [comment]
that already happens

https://github.com/tobymao/saq/blob/master/saq/worker.py#L61

on windows, only sigterm is set, not sigint. it looks like sigterm should be handled by windows

**Comment by espdev** [comment]
On Windows we can use signals anyway to graceful shutdown worker.
For example, we can use roughly the following code:

```python
# worker.py

async def start(self) -> None:
    try:
        self.event = asyncio.Event()

        def set_event(*args):
            self.event.set()

        signal.signal(signal.SIGINT, set_event)
        signal.signal(signal.SIGTERM, set_event)
```

**Comment by HairlessVillager** [comment]
@espdev Hi, would you like to push your update to your repo? I wanna try it🧐
